### ISSUE TITLE
OTG-HW binding for Ondatra-featureprofile to run OTG test

### ISSUE THREAD

**Issue by alakendu** [openconfig/ondatra#36]
## Requirements
- gRPC, gNMI, Ixia-c and OTG-HW are deploy using docker compose and connected to HW chassis.
- gRPC and gNMI server endpoint are required to run OTG test in featureprofile
- User have to configure Chassis IP, Card, Port and Speed information in binding or testbed file.

<h4 align="center">
<img src="https://user-images.githubusercontent.com/35574510/188153468-2158c907-e953-430c-886a-005ff8ab2700.png" width="550">
</h4>

## Proposal
- We will utilize StaticBinding present in featureprofile to run IxNetwork HW ATE test.
- OTG test must be execute: 
```
cd ./topologies/otg_tests/topology_test
go test -v . -testbed ../../atedut_2.testbed -binding ../../atedut_2.binding
```
- Expose another property called `otg` within <a href="https://github.com/openconfig/featureprofiles/blob/b498275403d31037b52ff63da817e29450cba706/topologies/proto/binding.proto#L47" target="_blank">device binding </a>
- This is a sample ate binding section within ../../atedut_2.binding
```yaml
ates {
  id: "ate"
  name: "10.39.33.143"  # Change this to the Ixia chassis name.

  # This option specific to OTG over Ixia-HW. 
  otg {
    target: "127.0.0.1:40051" # Change this to the Ixia-c-grpc server endpoint.
  }

  gnmi {
    target: "127.0.0.1:50051"  # Change this to the Ixia-c-gnmi server endpoint.
  }

  # Before this binding can be used with a topology, add ports mapping
  # from its topology ID to the actual port name on the device.
  ports {
    id: "port1"
    name: "2/5"  # Change this to the actual port name.
  }
  ports {
    id: "port2"
    name: "2/6"  # Change this to the actual port name.
  }
}
```

**Comment by SubhajitPalKeysight** [comment]
@jasdeep-hundal  @greg-dennis  Would you please offer your feedback and comment on this.

**Comment by greg-dennis** [comment]
Please give us a week to review as we have current Sprint tasks that need to be complete. Added @liulk for any comments he may have on the static binding changes.

**Comment by liulk** [comment]
Does ixia-c really need to run inside a container as opposed to a standalone binary? Docker seems rather heavyweight. If we can run ixia-c gnmi/snappi server, controller, and hw controller from a shell script as an unprivileged user, then the static binding can just start them on demand and use reasonable defaults for the otg/gnmi ports.

By the way, the name of the dial options fields refer to the protocol or service that we expect to find there rather than the API. I know that `otg` is the API, but is it also the name of the gRPC service?

**Comment by alakendu** [comment]
As per communication with @greg-dennis 
_1. We prefer it to be deployed as a docker container. We envision it replacing the dockerized IxNetwork that we have recently enabled. 
2. We have a preference for docker compose, because we know we know Google Linux installations provide that already._

This is a new docker which has a relatively lesser memory footprint compared to regular IxNetwork.

I have proposed `otg` name as we are planning to reuse `DialOTG` for this static binding. Your concern is also valid. There are few names I can think of `otghw` or `ixiachw`

**Comment by liulk** [comment]
Yes, Greg and I also talked about this yesterday, and he brought up the possibility of running the Ixia-C docker on a different host than the test as a long running service. Also, as far as the static binding is concerned, it makes sense that the otg represents the hw chassis and therefore are synonymous.

I think given that, otg seems like a reasonable name for the dial option.

**Comment by jasdeep-hundal** [comment]
@alakendu:
- The diagram you posted shows the test running on the same Linux machine as the ixia-c containers. Can you confirm that it's not necessary for a test to run on the same machine?
- Is it possible for multiple tests to use the same ixia-c instance simultaneously? (Is there a similar concept to 'sessions' on IxNetwork?)
- Can you clarify 'name' in the comment "# Change this to the Ixia chassis name.". Does 'name' refer to the host/domain name of the chassis (and therefore could actually be IP as well), or does it mean something else?
- How is ixia-c itself configured with the physical chassis IP/hostname? Is that done per-test session, or is it configured at the container level? Related question: can one ixia-c deployment configure multiple physical chassis?
- The DialIxNetwork method (https://github.com/openconfig/ondatra/blob/5011bd208d4891267620692c6f23af5c55ca01e4/binding/binding.go#L163) of the ATE Interface returns an IxNetwork type that includes an optional chassis IP because an IxNetwork instance may not be able to resolve the chassis hardware ports using the same host/domain name as listed in the ATE configuration. Do we need to provide a similar mechanism through DialOTG?

**Comment by alakendu** [comment]
Please find inline comments: 
> * The diagram you posted shows the test running on the same Linux machine as the ixia-c containers. Can you confirm that it's not necessary for a test to run on the same machine?

 Yes, user can run test from any system 

> * Is it possible for multiple tests to use the same ixia-c instance simultaneously? (Is there a similar concept to 'sessions' on IxNetwork?)

No, It is not possible. 

> * Can you clarify 'name' in the comment "# Change this to the Ixia chassis name.". Does 'name' refer to the host/domain name of the chassis (and therefore could actually be IP as well), or does it mean something else?

Yes, `name` could be IP-address/ host name

> * How is ixia-c itself configured with the physical chassis IP/hostname? Is that done per-test session, or is it configured at the container level? Related question: can one ixia-c deployment configure multiple physical chassis?

`ixia-c` work as a proxy. `Ixia-c-HW` docker responsible to configure physical chassis.
`Ixia-c-HW` can run against multiple physical chassis. But, I feel staticBinding have limitation to run multiple chassis if we consider similar IxNetwork concept.


> * The DialIxNetwork method (https://github.com/openconfig/ondatra/blob/5011bd208d4891267620692c6f23af5c55ca01e4/binding/binding.go#L163
   ) of the ATE Interface returns an IxNetwork type that includes an optional chassis IP because an IxNetwork instance may not be able to resolve the chassis hardware ports using the same host/domain name as listed in the ATE configuration. Do we need to provide a similar mechanism through DialOTG?

] I feel you are referring to (https://github.com/openconfig/ondatra/blob/5011bd208d4891267620692c6f23af5c55ca01e4/internal/ate/topology.go#L57)
 
Yes, for ixia-c-hw also require similar mapping. At the same time our plan is to run OTG test against ixia-c-hw. But, `DialOTG` interface will return `gosnappi.GosnappiApi`. So, I am thinking to overwrite port name at the time of reservation.
```go
        if bd.Otg != nil {
                 p.Name = fmt.Sprintf("%s;%s", bd.Name, strings.ReplaceAll(bport.Name, "/", ";"))
        } else {
                 p.Name = bport.Name
        }
```

As an alternative we also think to provide port location within port name
  
```yaml
ports {
    id: "port1"
    name: "10.39.33.143;1;1"
}
```

**Comment by greg-dennis** [comment]
@alakendu For the time being, I think it makes sense for the port name to be written to the "fully-qualified location" of the port that includes the chassis hostname/IP.

However, separately, I'd like to see an FR that allows the option of a global/default location at the GoSnappi level. If specified, none of the individual port locations need to be specified -- the names of the ports alone suffice. We have something close to that in KNE today: the locations do need to be specified but they can be the local interfaces names of the ports rather than the fully-qualified location. I'm suggesting we go further such that the individual port locations would never need to be specified, even for HW, in the presence of a global location being set. Thoughts?

**Comment by alakendu** [comment]
@greg-dennis Thanks!

**Comment by greg-dennis** [comment]
Great! Closing issue as the design seems substantially resolved and reviewed.
