### ISSUE TITLE
LookupConfig fails test when path does not exist

### ISSUE THREAD

**Issue by kjahed** [openconfig/ondatra#62]
Currently, LookupConfig on a path that does not exist causes the test to fail whenever the server returns NOT_FOUND (and useGetForCfg is set). This causes multiple featureprofiles tests to fail.

According to the [specs](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#334-getresponse-behavior-table) NOT_FOUND is the expected response. However, shouldn't LookupConfig handle that error by setting value.present to false? or at least, shouldn't errors be returned to the tests to deal with rather than failing the tests? I believe that was the behaviour in the old API.

**Comment by greg-dennis** [comment]
Could please clarify why tests are failing? Are they failing because the NOT_FOUND error is being propagated back up to the test? If that is the case, that is a bug that needs to be fixed in ygnmi.

The specification of LookupConfig is that it is supposed to behave like a ONCE subscription:
https://github.com/openconfig/ondatra/blob/0dbcef7d1528655072a0ea9feaf90de8d702fd6f/gnmi/gnmi.go#L114

Since some vendors do not yet support Subscribe for config paths, we added the useGetForCfg option, which uses Get in the background and adapts it to behave like a ONCE subscribe. A subscribe should not return NOT_FOUND, so again, if that is happening, that needs to be fixed.

**Comment by kjahed** [comment]
That's right. NOT_FOUND is being propagated back to the test. Here's there error we see

`gnmi.go:118: Lookup(t) on dut(SF-D) at &{{System_Ntp_Server false 0xc0008bc170 [] 0xc00397ec00}}: failed to subscribe to path: gNMI failed to Send(subscribe:{prefix:{target:"SF-D"} subscription:{path:{origin:"openconfig" elem:{name:"system"} elem:{name:"ntp"} elem:{name:"servers"} elem:{name:"server" key:{key:"address" value:"[192.0.2.1](https://192.0.2.1/)"}}}} mode:ONCE encoding:PROTO}): rpc error: code = NotFound desc = error on request { prefix: { target: "SF-D" } path: { origin: "openconfig" elem: { name: "system" } elem: { name: "ntp" } elem: { name: "servers" } elem: { name: "server" key: { key: "address" value: "[192.0.2.1](https://192.0.2.1/)" } } } type: CONFIG encoding: JSON_IETF }: Requested element(s) not found: '[server]'`

**Comment by greg-dennis** [comment]
Thanks for reporting! We hope to have a fix to ygnmi by the end of day.

**Comment by greg-dennis** [comment]
Can you upgrade your version of ygnmi to the just-released v0.7.2 and confirm the issue goes away?

**Comment by kjahed** [comment]
Can confirm v0.7.2 fixes the issue. Thank you for the quick resolution!

**Comment by greg-dennis** [comment]
The ygnmi version has been bumped in Ondatra
