### ISSUE TITLE
Misleading grpc logs

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#71]
Hi, we recently observed a new issue concerning the logging of grpc requests that is misleading.
It seems that ondatra correlates the eof error at the end of the grpc session with the last request which is not right. for example I use gribi to program the following entry and then restart the gribi service that will result in an expected eof, however, ondatra correlated the eof with the last request which was successfully processed.

here is the log shows the entry is successfully programmed:
```
I0323 15:36:04.611060    4472 gribiclient.go:372] sent Modify message operation:{id:3  network_instance:"DEFAULT"  op:ADD  ipv4:{prefix:"[203.0.113.0/24](https://www.google.com/url?q=http://203.0.113.0/24&sa=D&source=buganizer&usg=AOvVaw1Um7cNzJXXgQalNtdhwMmz)"  ipv4_entry:{next_hop_group:{value:42}}}  election_id:{low:2}}
I0323 15:36:04.656613    4471 gribiclient.go:318] received message on Modify stream: result:{id:3  status:RIB_PROGRAMMED  timestamp:1679610964653535635}
```
and here is the ondatra logs after expected eof that reports the last request was failed due to eof

```
E0323 15:39:21.101732    4471 gribiclient.go:327] got error receiving message, rpc error: code = Unavailable desc = error on request {
operation:  {
  id:  3
  network_instance:  "DEFAULT"
  op:  ADD
  ipv4:  {
    prefix:  "[203.0.113.0/24](https://www.google.com/url?q=http://203.0.113.0/24&sa=D&source=buganizer&usg=AOvVaw1Um7cNzJXXgQalNtdhwMmz)"
    ipv4_entry:  {
      next_hop_group:  {
        value:  42
      }
    }
  }
  election_id:  {
    low:  2
  }
}
}: error reading from

```

**Comment by greg-dennis** [comment]
@mojiiba, sorry for the delay. A few notes on this:

As far as I can see, this is a gRPC Unavailable error, not an EOF error.

A gRPC streaming RPC, like the Modify RPC, may have any number of responses that are received in response to a single request. In general, just because a single successful response is received after a request, subsequent messages received due to that request may fail.

A `RIB_PROGRAMMED` message was received, but an incorrectly implemented server could send an erroneous response to the same request after that point.

The Modify request in the log above is the proximate request to the receive attempt that failed, so it still seems relevant. Do you agree? There's no way to tell that the request _caused_ the error, per se, but it did occur when on a response to the request.

Do you think the error message would be better if it said "error after request" instead of "error on request"?

**Comment by greg-dennis** [comment]
I made a small modification to the error message internally to help clarify this. It will be part of the next release.
