### ISSUE TITLE
OTG does not support NewConfig API

### ISSUE THREAD

**Issue by lyle-thompson-keysight** [openconfig/ondatra#91]
When working with OTG, I have to import gosnappi just to create a new config before using the OTG object to push it. Later, when I upgrade to a new ondatra, I also have to update the gosnappi anchor to match the OTG anchor. Not a huge deal, but it's a friction point when using your API. Please add NewConfig or an equivalent API to the OTG object.

**Comment by greg-dennis** [comment]
There is intentionally no `NewConfig` call on the OTG object itself, because `NewConfig` is independent of the particular OTG connection. The Config can be created and customized independently of any particular device. Requiring there be an active OTG object and would raise unclear questions, such as whether a config created from one OTG instance could be set on another.
