### ISSUE TITLE
Errors after go generate ./...

### ISSUE THREAD

**Issue by 6303210121** [openconfig/ondatra#97]
hi,
we installed protobuf using sudo apt install -y protobuf-compiler
Then ,wwe run go generate ./... we encountered with the below errors.I have no idea how to rectify those errors.Can anyone who have idea can help me and howq to resolving the issue.Here I am attaching my results.Please check it once.
[user1~sampleondatraknebindintegration$ sudo apt install -y protobuf-compiler.pdf](https://github.com/openconfig/ondatra/files/13987720/user1.sampleondatraknebindintegration.sudo.apt.install.-y.protobuf-compiler.pdf)

**Comment by greg-dennis** [comment]
In general, it's not worth running through more commands when earlier commands failed. In future issues, please try to limit it to just the first failure. In these logs, I see two things:

1. You should be using go 1.21, not 1.19, as the go.mod file requires:
https://github.com/openconfig/ondatra/blob/main/go.mod#L3

2. You have an early failure because you don't have protoc-gen-go installed.  It says "protoc-gen-go: program not found or is not executable" in the log you provided. You should be able to take care of that by installing it in your repo: `go install google.golang.org/protobuf/cmd/protoc-gen-go@latest`

**Comment by greg-dennis** [comment]
I will close this and deal with your latest issue in https://github.com/openconfig/ondatra/issues/98
